
networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:14-alpine
    container_name: sales_daily_db
    environment:
      POSTGRES_USER: salesuser
      POSTGRES_PASSWORD: salespass
      POSTGRES_DB: sales_daily
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: sales_daily_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  api:
    build: ./server
    container_name: sales_daily_api
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=3002
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: sales_daily_frontend
    environment:
      - VITE_API_URL=http://api:3002
      - NODE_ENV=development
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
