
services:
  postgres:
    image: postgres:14-alpine
    container_name: sales_daily_db
    environment:
      POSTGRES_USER: salesuser
      POSTGRES_PASSWORD: salespass
      POSTGRES_DB: sales_daily
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./server
    container_name: sales_daily_api
    env_file:
      - .env.docker
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build: ./client
    container_name: sales_daily_frontend
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  postgres_data:
